.ifndef MEMORY_MAP_VRAM_INC
MEMORY_MAP_VRAM_INC = 1
; -----------------------------------------------------------------------------
;   File: MemoryMapVRAM.inc
;   Description: Symbols representing addresses in VRAM
; -----------------------------------------------------------------------------

;----- Memory Map VRAM ---------------------------------------------------------
SPRITE_CHARS    = $0000
BG1_CHARS       = $1000
BG1_TILEMAP     = $4000
;-------------------------------------------------------------------------------

.endif
